services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    restart: always
    environment:
      - "CF_API_EMAIL=${CF_API_EMAIL}"
      - "CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}"
    networks:
      traefik:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      #- "22:22"
      #- "25:25"
      #- "465:465"
      #- "993:993"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  traefik-certs-dumper:
    image: "ghcr.io/kereis/traefik-certs-dumper:latest"
    container_name: "traefik-certs-dumper"
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./letsencrypt:/traefik:ro"
      - "traefik_certs:/output"

networks:
  traefik:
    external: true

volumes:
  traefik_certs:
    external: true
